"""Add notes to Wishlist model

Revision ID: 011d0b2c313d
Revises: 84651363e3bb
Create Date: 2024-10-12 21:20:38.780883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011d0b2c313d'
down_revision = '84651363e3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
