"""Add bought field to Wishlist model

Revision ID: cdd509125dd2
Revises: 011d0b2c313d
Create Date: 2024-10-12 21:28:18.172794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd509125dd2'
down_revision = '011d0b2c313d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_column('bought')

    # ### end Alembic commands ###
